### ISSUE TITLE
Create xibo module

### ISSUE THREAD

**Issue by henriquelucas** [DevWithReact/custom-xibo-modules#1]
I would like to know how much would you charge to make a custom xibo module. Basically what I need is for lottery numbers to be displayed. I already have something ready that does this, I just need to integrate it into the xibo module.

```
<?php
       $texto = file_get_contents('http://www.lotterytaiwan.com/intl/BR/results.js');
        
        $filtro = strchr($texto, 'var draw_BRMS=new Array('); //procura a string
        $item = strchr($filtro,')', true); // corta a parte interessada
        $numeros = strchr($item, '"'); // deixa somente os numeros

        $numeros_sem_aspas = str_replace('"','',$numeros); // formata string...
        $numeros_sem_virgula = str_replace(',',' ',$numeros_sem_aspas);
        
        echo $numeros_sem_virgula; //saida: 11 16 20 24 39 53 
        
?>
```
Thank you in advance for your attention.

**Comment by dream-topdev** [comment]
@henriquelucas Nice to meet you. Can we discuss in more detail?
Please leave me your skype or telegram/whatsapp.
Hope to chat with you.

**Comment by henriquelucas** [comment]
Whatsapp: +55 83 998014235

**Comment by dream-topdev** [comment]
@henriquelucas  do you use telegram?

**Comment by dream-topdev** [comment]
@henriquelucas  I'm on what's app. let's chat.
